language: java
sudo: false # faster builds
before_script:
  - pip install --user codecov
jdk:
  - oraclejdk8
after_success:
#  - coveralls
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - codecov
