language: java
sudo: false # faster builds
before_script:
  - pip install --user codecov
jdk:
  - oraclejdk8
after_success:
  - codecov
  - mvn clean cobertura:cobertura -Dcobertura.report.format=xml org.eluder.coveralls:coveralls-maven-plugin:report
  - coveralls